name: publish-book

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    secrets:
      EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USER }}
      EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASS }}

  deploy:
    needs: build
    uses: ProjectPythia/cookbook-actions/.github/workflows/deploy-book.yaml@main
